version: "3.9"
services:
  client:
    image: serialoverwebsocketclient
    volumes:
      - config:/app/Settings
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  config: